const defaultTopPermission = [
  "helloPage",
  "homePage",
  "sysPage",
  "rolePage",
  "index:Add",
  "index:EDIT",
  "index:DELETE",
  "index:IMPORT",
  "index:EXPORT",
  "userPage:Add",
  "userPage:EDIT",
  "userPage:DELETE",
  "userPage:IMPORT",
  "rolePage:Add",
  "rolePage:EDIT",
  "rolePage:DELETE",
  "rolePage:IMPORT",
  "rolePage:EXPORT",
  "userPage",
  "rolePage:ADD",
  "userPage:EXPORT",
];

export default defaultTopPermission;
